### ISSUE TITLE
As a client, I would like to have a "create" button to add my budget items easily.

### ISSUE THREAD

**Issue by egebgs** [SU-CS308-22FA/CS308-202201-Team06-FMS#26]
# Acceptance Criteria

## Basic
- Teams can see the create budget item button on login ✔ 
- Teams can click on the button to fill out the new budget item form ✔ 
- Teams can submit the form to create a new budget item ✔ 
- Teams can see the newly created budget item on the list ✔ 

##  Edge Cases
- Display error message when trying to insert duplicates ✔

**Comment by zgr2788** [comment]
Approved for testing
